p8105_hw2_jm5916
================
Juhi Mattekatt
2025-09-30

# Problem 1

``` r
#read data in 
pols_month <- read_csv(file = "./fivethirtyeight_datasets/pols-month.csv")
unemployment <- read_csv(file = "./fivethirtyeight_datasets/unemployment.csv")
snp <- read_csv(file = "./fivethirtyeight_datasets/snp.csv")
#check datasets in console
```

I’ve imported the three datasets in using relative paths. The files are
in the fivethirtyeight_datasets folder within my subdirectory for this
homework. I viewed the data (in console) and checked to see how the
names were formatted.

``` r
#clean pols_month for merging
pols_month_merge <- pols_month %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% #break up the variable mon
  mutate(
    year = as.integer(year), #make year, month, and day integer variables, use as.integer to prevent dropping of leading 0s
    month = as.integer(month), 
    day = as.integer(day),
    month = month.name[month], #replace month number with month name
    president = case_when( #use mutate and case when to create new variable president
      prez_dem == 1 & prez_gop == 0 ~ "dem", 
      prez_gop == 1 & prez_dem == 0 ~ "gop") ) %>% 
  select(-prez_dem, -prez_gop, -day) %>%  #remove columns
  arrange(year, month) #arrange by year and month

#clean snp for merging 
snp_merge <- snp %>%  
  separate(date, into = c("month", "day", "year"), sep = "/") %>% #break up the variable date
  mutate( #mutate to change values
    year = case_when( #case when to add start of year to values in year
      0 <= as.numeric(year) & as.numeric(year) <= 15 ~ paste0("20", year), 
      50 <= as.numeric(year) & as.numeric(year) <= 99 ~ paste0("19", year)),
    year = as.numeric(year), #make year, month, and day integer variables
    month = as.numeric(month), 
    day = as.numeric(day),
    month = month.name[month]) %>% #replace month number with month name  
  select(-day) %>% #remove columns 
  arrange(year, month) %>% 
  relocate(year, month) #move year and month to front

#clean unemployment for merging
unemployment_merge <- unemployment %>%  
  pivot_longer( #pivot from wide to long format
    Jan:Dec,
    names_to = "month_abb", #make new variable month_abb for abbreviated months
    values_to = "%_unemployment") %>% 
  rename(year = Year) %>% #make sure year isn't capitalized
  mutate( #make new variable month with full month names to match other datasets
    month = month.name[match(month_abb, month.abb)]) %>% #convert abbreviated to full name
  arrange(year, month) %>% 
  relocate(year, month) %>% 
  select(-month_abb) #remove abbreviated month column
```

I’ve created 3 new datasets (I kept the old datasets as is in case I
made any mistakes while cleaning the data since there were a lot of
changes, I’ve removed intermediate datasets in the other problems) to
make the keys I’m joining by compatible with each other.

``` r
#left join unemployment and snp into pols_month
pols_snp_unemployment <- pols_month_merge %>% 
  left_join(snp_merge, by = c("year", "month")) %>% 
  left_join(unemployment_merge, by = c("year", "month"))
```

### Explanation

The dataset `pols_month` contains information on the number of national
politicians (president, senators, governors, and representatives) who
are democratic or republican at some time point. `snp` indicates the
closing values of the S&P stock index at a given date, and
`unemployment` identifies % unemployment for every month of a given
year. My final dataset `pols_snp_unemployment` has 822 rows and 11
columns and combines all the information from the above datasets for the
years and months described in `pols_month`. Overall, there will be data
on political parties in power and economic indicators for a time period.
The years range from 1947 to 2015, and key variables include
`president`, `close`, and `%_unemployment`.

# Problem 2

``` r
library(readxl) #to import excel files, already had package installed 

#import Mr. Trash Wheel data, omit first row with figure and last row with sums
Mr_TW <- 
  read_excel("./202509 Trash Wheel Collection Data.xlsx", 
    sheet = "Mr. Trash Wheel", range = "A2:N709") %>% 
  #clean Mr_TW
  janitor::clean_names() %>% #make names snake case
  mutate(
    sports_balls = round(sports_balls, 0), #round sports_balls to nearest integer
    sports_balls = as.integer(sports_balls), #convert to an integer variable
    trash_wheel = "Mr") %>% #add new variable to keep track of which Trash Wheel is which
  relocate(trash_wheel)

#import Professor Trash Wheel data, omit first row with figure and last row with sums
Prof_TW <- 
  read_excel("./202509 Trash Wheel Collection Data.xlsx", 
      sheet = "Professor Trash Wheel", range = "A2:M134") %>% 
  #clean Prof_TW
  janitor::clean_names() %>% #make names snake case
  mutate(
    trash_wheel = "Prof") %>% #add new variable to keep track of which Trash Wheel is which
  relocate(trash_wheel)

#import Gwynns Falls Trash Wheel data, omit first row with figure and last row with sums
Gwy_TW <- 
  read_excel("./202509 Trash Wheel Collection Data.xlsx", 
      sheet = "Gwynns Falls Trash Wheel", range = "A2:L351") %>% 
  #clean Prof_TW
  janitor::clean_names() %>% #make names snake case
  mutate(
    trash_wheel = "Gwynns") %>% #add new variable to keep track of which Trash Wheel is which
  relocate(trash_wheel)
```

I imported and prepared the 3 datasets to be combined.

``` r
#running the combining code the first time didn't work because "year" was numeric in one dataset and a character in another. I'll make year in every dataset a character.
Mr_TW <- Mr_TW %>% 
  mutate(year = as.character(year))
Prof_TW <- Prof_TW %>% 
  mutate(year = as.character(year))
Gwy_TW <- Gwy_TW %>% 
  mutate(year = as.character(year))

#combine the datasets          
TW_tidy <- bind_rows(Mr_TW, Prof_TW, Gwy_TW)
```

### Explanation

`TW_tidy` contains information on the types and amounts of trash
collected by 3 trash wheels (Mr. Trash Wheel, Professor Trash Wheel, and
the Gwynns Falls Trash Wheel/Gwynnda) from 2014-2025. There are 1188
observations. Some key variables include `date` (date dumpster was
collected), `weight_tons` (weight of each dumpster in tons),
`volume_cubic_yards` (volume of waste collected from each dumpster in
cubic yards), and `homes_powered` (number of homes powered by waste
collected). The total weight of trash collected by Professor Trash Wheel
was 282.26 tons. There was no missing data for `weight_tons`. The total
number of cigarette butts collected by Gwynnda in June of 2022 was
18120.

# Problem 3

``` r
#import datasets 
zip <- read_csv("./zillow_data/Zip Codes.csv") %>% 
    janitor::clean_names() %>% #make names snake case
    distinct(zip_code, .keep_all = TRUE)
zori <- read_csv("./zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")%>% 
    janitor::clean_names() #make names snake case
```

I imported the datasets, viewed the data, and cleaned their names.

``` r
#clean zori for merging
zori<- zori %>% 
  rename(zip_code = region_name) %>% #zip code is under region_name in zori rename
  pivot_longer( #zori is spread out over multiple columns so I'll condense 
    x2015_01_31:x2024_08_31,
    names_to = "date", 
    names_prefix = "x",
    values_to = "zori") %>% 
  filter(!is.na(zori)) %>% #remove rows without any zori info
  separate(date, into = c("year", "month", "day"), sep = "_") %>% #maintain data integrity
  mutate( #change month numbers into words
    month = as.integer(month),
    month = month.name[month])

#join datasets by zip code
zip_zori = right_join(zip, zori, by = "zip_code") %>% #join zip to zori
  select(zip_code, neighborhood, county, year, month, day, zori) %>%  #only keep important info
  arrange(zip_code, year) #sort by zip code and year
```

### Explanation

`zip_zori` shows the average rent price by zip code and date.
Unnecessary information from `zip` and `zori` were removed for ease of
reading. There are 10450 observations. There are 149 unique zip codes
and 42 unique neighborhoods.

### Compare zip codes in the datasets

``` r
in_zip_not_zori = anti_join(zip, zori, by = "zip_code") %>% #see which zip codes are not shared
  relocate(zip_code)

#show all zip codes that exist only in zip
in_zip_not_zori$zip_code
```

    ##   [1] 10464 10474 10475 10499 10550 10704 10705 10803 11202 11224 11239 11241
    ##  [13] 11242 11243 11245 11247 11251 11252 11256 10008 10020 10041 10043 10045
    ##  [25] 10047 10048 10055 10072 10080 10081 10082 10087 10101 10102 10103 10104
    ##  [37] 10105 10106 10107 10108 10109 10110 10111 10112 10113 10114 10115 10116
    ##  [49] 10117 10118 10119 10120 10121 10122 10123 10124 10125 10126 10129 10130
    ##  [61] 10131 10132 10133 10138 10149 10150 10151 10152 10153 10154 10155 10156
    ##  [73] 10157 10158 10159 10160 10161 10163 10164 10165 10166 10167 10168 10169
    ##  [85] 10170 10171 10172 10173 10174 10175 10176 10177 10178 10179 10185 10197
    ##  [97] 10199 10213 10242 10249 10256 10259 10260 10261 10265 10268 10269 10270
    ## [109] 10271 10272 10273 10274 10275 10276 10277 10278 10279 10281 10285 10286
    ## [121] 10292 11001 11004 11005 11040 11096 11351 11352 11359 11362 11363 11371
    ## [133] 11380 11381 11386 11405 11411 11412 11413 11414 11416 11417 11419 11420
    ## [145] 11421 11422 11423 11424 11425 11427 11428 11429 11430 11431 11433 11436
    ## [157] 11439 11451 11499 11559 11580 11690 11694 11695 11697 10302 10307 10309
    ## [169] 10310 10311 10313

There are 171 zip codes in the ZIP code dataset that are not in the
Zillow Rental Price dataset. There are a number of reasons why these zip
codes aren’t included in the Zillow Rental Price dataset. One of the zip
codes is 10474 in the Bronx, this is a pretty industrial area and there
may not be many places to rent in this zip code. As such, Zillow might
not report this data. 10020 in Midtown is another example of a zip code
with more commerce than residence. Another reason is that some zip codes
are wealthy, and people living in these areas will be homeowners rather
than renters, thus their zip codes wouldn’t be included in a rental
price dataset. This could be the case for 11224, which includes the
gated community of Seagate. Many of the zip codes in Richmond county
(Staten Island) may fall under this category due to many people in
Staten Island being homeowners. Another reason could be that the zip
codes may include areas that Zillow doesn’t consider part of NYC, for
instance 10705 and 10704 both go into Yonkers, so data on rental prices
there may not be put into a dataset specific to NYC.

### Rental prices fluctuations

``` r
price_flex <- zip_zori %>% 
  filter((year == 2020 & month == "January") | (year == 2021 & month == "January")) %>%
  pivot_wider(
    names_from = year, 
    values_from = zori,
    names_prefix = "zori_") %>%
  mutate(
    price_fluctuation = round(zori_2021 - zori_2020, 2),
    borough = recode(county,
                     "New York" = "Manhattan",
                     "Brooklyn" = "Kings",
                     "Staten Island" = "Richmond")) %>%
  select(zip_code, neighborhood, borough, price_fluctuation) %>%
  arrange(price_fluctuation) %>% 
  slice(1:10)

#view table in file
knitr::kable(price_flex)
```

| zip_code | neighborhood                  | borough   | price_fluctuation |
|---------:|:------------------------------|:----------|------------------:|
|    10007 | Lower Manhattan               | Manhattan |           -912.60 |
|    10069 | NA                            | Manhattan |           -748.12 |
|    10009 | Lower East Side               | Manhattan |           -714.25 |
|    10016 | Gramercy Park and Murray Hill | Manhattan |           -711.70 |
|    10001 | Chelsea and Clinton           | Manhattan |           -710.45 |
|    10002 | Lower East Side               | Manhattan |           -710.30 |
|    10004 | Lower Manhattan               | Manhattan |           -705.96 |
|    10038 | Lower Manhattan               | Manhattan |           -697.59 |
|    10012 | Greenwich Village and Soho    | Manhattan |           -686.22 |
|    10010 | Gramercy Park and Murray Hill | Manhattan |           -684.93 |

Lower Manhattan saw the largest drops in rental prices during the
COVID-19 pandemic. This may be in part due to lower Manhattan having
among the highest rent prices in the city. These prices would have been
unsustainable during an increased cost of living crisis and decreased
job security, so landlords likely had to lower rent prices greatly.
